@startuml
class Bullet {
    + damage : int = 10
    - speed : float = 10f
    - _hasAlreadyHitEnemy : bool
    - Update() : void
    - OnTriggerEnter2D(col:Collider2D) : void
}
class "Action`1"<T> {
}
MonoBehaviour <|-- Bullet
Bullet --> "OnEnemyHit<Enemy>" "Action`1"
@enduml
