@startuml
class "Enemy : MonoBehaviour" as Enemy {
    - speed : float = 5f
    - startHealth : float = 100f
    - bodyCornerTurnSpeed : float = 0.1f
    - turretCornerTurnSpeed : float = 0.1f
    - turretRotationSpeedMinMax : Vector2 = {1f, 2f}
    - turretRotationAmount : float = 45f
    - moneyValue : int = 10
    - cashNotifPrefab : GameObject
    + Damage(amount:float) : void
    + Debuff(factor:float, duration:float, visual:GameObject) : void
}
@enduml
