@startuml
class "Tower : MonoBehaviour" as Tower {
    + price : int = 100
    - range : float = 3f
    - fireRate : float = 1f
    - bulletPrefab : GameObject
    - upgradeTowerPrefab : GameObject
    - _target : Enemy
    + GetNextUpgrade() : GameObject?
}
Tower --> "_target" Enemy
@enduml
