@startuml
abstract class "ABulletEffect : MonoBehaviour" as ABulletEffect <<Bullet>> {
    # Bullet : Bullet <<get>>
    # {abstract} OnEnemyHit(enemy:Enemy) : void
}
ABulletEffect --> "Bullet" Bullet
@enduml
