@startuml
class Debuff <<Bullet>> {
    - speedFactor : float = 0.5f
    - duration : float = 2f
    - visualEffectPrefab : GameObject
    # <<override>> OnEnemyHit(enemy:Enemy) : void
}
ABulletEffect <|-- Debuff
@enduml
