@startuml
class "Wave : ScriptableObject" as Wave {
    + delaySincePreviousWave : int
    - waveParts : WavePart[]
    + StartWave() : void
}
class WavePart {
    + enemyPrefab : GameObject
    + enemyCount : int
}
Wave --> "waveParts" WavePart
@enduml
