@startuml
class Wave {
    + delaySincePreviousWave : int
    - OnValidate() : void
    + StartWave() : void
}
class WavePart {
    + enemyCount : int
}
ScriptableObject <|-- Wave
WavePart --> "enemyPrefab" GameObject
@enduml
