@startuml
class "PlayerStatsManager : MonoBehaviour" as PlayerStatsManager {
    + {static} Instance : PlayerStatsManager
    - startHealth : int = 20
    - startMoney : int = 200
    - sellMultiplier : float = 0.5f
    - statsText : TMP_Text
    + TakeDamage(damage:int) : void
    + Sell(price:int) : void
    + AddMoney(amount:int) : void
    + Buy(price:int) : void
    + HaveEnoughMoneyFor(price:int) : bool
}
PlayerStatsManager --> "Instance" PlayerStatsManager
@enduml
