@startuml
class "WaveManager : MonoBehaviour" as WaveManager {
    + {static} Instance : WaveManager
    + OnWaveStart : Action
    + OnWaveEnd : Action
    + IsWaveRunning : bool <<get>>
    - strPrepareToBeAttackedByWave : string = "Prepare to be attacked by wave {0}"
    - strTimeTillNextWave : string = "Time till next wave: {0}"
    - strCurrentWave : string = "Current wave: {0}"
    - waves : Wave[]
    - waveText : TMP_Text
    - waveCountdownText : TMP_Text
    - {static} WaitForAllEnemiesDefeated() : IEnumerator
    + {static} GetEnemies() : Enemy[]
}
WaveManager --> "Instance" WaveManager
WaveManager --> "waves" Wave
WaveManager --> "GetEnemies()" Enemy
@enduml
